site_name: TimeSlip

# Meta tags (placed in header)
site_description: Time manipulation for JVM test cases
site_url: https://timeslip.hypercubetools.com

# Repository (add link to repository on each page)
repo_name: timeslip
repo_url: https://github.com/plannigan/timeslip
edit_uri: edit/master/src/doc/docs/

theme:
  name: 'material'
  palette:
    primary: 'grey'
    accent: 'indigo'
  logo:
    icon: "timelapse"
extra:
  homepage_sidebars:
    - about
    - toc
    - search
  sidebars:
    - about
    - navigation
    - toc
    - search
  logo_title: "TimeSlip logo"
  show_powered_by: false

extra_css:
  - css/code-tabs.css

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - markdown_include.include:
      base_path: docs
  - toc:
      permalink: "¶"
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.superfences
  - markdown_fenced_code_tabs:
      template: 'default'

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Usage guide: usage-guide.md
  - Release Notes: history.md
